version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tickets-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: tickets-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: ticket
      SPRING_DATASOURCE_PASSWORD: ticket123
      SECURITY_JWT_SECRET: bdu1ijtyjetq5kimuqb8yon3khvwt661
    ports:
      - "8080:8080"

volumes:
  pgdata:
